version: '3.8'

services:
  # Banco de Dados Único
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: restaurante_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Cache Redis
  redis-cache:
    image: redis:alpine
    container_name: redis-cache

  # CENÁRIO A: Cluster com Problemas (Legacy)
  sistema-legacy:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/restaurante_db
      - SPRING_PROFILES_ACTIVE=slow
      - JAVA_OPTS=-Xmx256m
    depends_on:
      - mysql-db

  # CENÁRIO B: Cluster Otimizado (Optimized)
  sistema-optimized:
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/restaurante_db
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_PROFILES_ACTIVE=fast
      - JAVA_OPTS=-Xmx1024m
    depends_on:
      - mysql-db
      - redis-cache

  # Load Balancer Nginx
  nginx-lb:
    image: nginx:alpine
    container_name: nginx-lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - sistema-legacy
      - sistema-optimized

volumes:
  mysql_data: