events { 
    worker_connections 1024; 
}

http {
    # Load Balance para o Cluster Lento
    upstream legacy_cluster {
        server sistema-legacy:8080;
    }

    # Load Balance para o Cluster Rápido
    upstream optimized_cluster {
        server sistema-optimized:8080;
    }

    server {
        listen 80;

        # Rota para o teste lento (Baseline)
        # URL no JMeter: http://localhost/legacy/api/restaurants/slow
        location /legacy/ {
            proxy_pass http://legacy_cluster/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Rota para o teste rápido (Otimizado)
        # URL no JMeter: http://localhost/optimized/api/restaurants/fast
        location /optimized/ {
            proxy_pass http://optimized_cluster/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}